name: Pell
favicon: null
layout_spectrum: 0.9542839773930609
typography_spectrum: 0.5029031641315669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.742610341636464
  lightness: 0.6606449410319328
  saturation: 0.16456941375508904
  rhythmicContrast: 0.2994667913299054
purpose: []
